// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'model.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Note.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// BEGIN TABLES
// Note TABLE
class TableNote extends SqfEntityTableBase {
  TableNote() {
    // declare properties of EntityTable
    tableName = 'notes';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = true;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text),
      SqfEntityFieldBase('data', DbType.text),
      SqfEntityFieldBase('syncId', DbType.text),
      SqfEntityFieldBase('favourite', DbType.bool, defaultValue: false),
      SqfEntityFieldBase('createdAt', DbType.datetime),
      SqfEntityFieldBase('updatedAt', DbType.datetime),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableNote();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9223372036854775807; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    databaseTables = [
      TableNote.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Note
class Note {
  Note(
      {this.id,
      this.title,
      this.data,
      this.syncId,
      this.favourite,
      this.createdAt,
      this.updatedAt,
      this.isDeleted}) {
    _setDefaultValues();
  }
  Note.withFields(this.title, this.data, this.syncId, this.favourite,
      this.createdAt, this.updatedAt, this.isDeleted) {
    _setDefaultValues();
  }
  Note.withId(this.id, this.title, this.data, this.syncId, this.favourite,
      this.createdAt, this.updatedAt, this.isDeleted) {
    _setDefaultValues();
  }
  Note.fromMap(Map<String, dynamic> o) {
    id = o['id'] as int;
    title = o['title'] as String;
    data = o['data'] as String;
    syncId = o['syncId'] as String;
    favourite = o['favourite'] != null ? o['favourite'] == 1 : null;
    createdAt = o['createdAt'] != null
        ? int.tryParse(o['createdAt'].toString()) != null
            ? DateTime.fromMillisecondsSinceEpoch(o['createdAt'] as int)
            : DateTime.tryParse(o['createdAt'].toString())
        : null;
    updatedAt = o['updatedAt'] != null
        ? int.tryParse(o['updatedAt'].toString()) != null
            ? DateTime.fromMillisecondsSinceEpoch(o['updatedAt'] as int)
            : DateTime.tryParse(o['updatedAt'].toString())
        : null;
    isDeleted = o['isDeleted'] != null ? o['isDeleted'] == 1 : null;
  }
  // FIELDS (Note)
  int id;
  String title;
  String data;
  String syncId;
  bool favourite;
  DateTime createdAt;
  DateTime updatedAt;
  bool isDeleted;

  BoolResult saveResult;
  // end FIELDS (Note)

  static const bool _softDeleteActivated = true;
  NoteManager __mnNote;

  NoteManager get _mnNote {
    return __mnNote = __mnNote ?? NoteManager();
  }

  // METHODS
  Map<String, dynamic> toMap({bool forQuery = false, bool forJson = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (data != null) {
      map['data'] = data;
    }

    if (syncId != null) {
      map['syncId'] = syncId;
    }

    if (favourite != null) {
      map['favourite'] = forQuery ? (favourite ? 1 : 0) : favourite;
    }

    if (createdAt != null) {
      map['createdAt'] = forJson
          ? createdAt.toUtc().toString()
          : forQuery ? createdAt.millisecondsSinceEpoch : createdAt;
    }

    if (updatedAt != null) {
      map['updatedAt'] = forJson
          ? updatedAt.toUtc().toString()
          : forQuery ? updatedAt.millisecondsSinceEpoch : updatedAt;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChilds(
      [bool forQuery = false, bool forJson = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (data != null) {
      map['data'] = data;
    }

    if (syncId != null) {
      map['syncId'] = syncId;
    }

    if (favourite != null) {
      map['favourite'] = forQuery ? (favourite ? 1 : 0) : favourite;
    }

    if (createdAt != null) {
      map['createdAt'] = forJson
          ? createdAt.toUtc().toString()
          : forQuery ? createdAt.millisecondsSinceEpoch : createdAt;
    }

    if (updatedAt != null) {
      map['updatedAt'] = forJson
          ? updatedAt.toUtc().toString()
          : forQuery ? updatedAt.millisecondsSinceEpoch : updatedAt;
    }

    if (isDeleted != null) {
      map['isDeleted'] = forQuery ? (isDeleted ? 1 : 0) : isDeleted;
    }

    return map;
  }

  /// This method always returns Json String
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method always returns Json String
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChilds(false, true));
  }

  List<dynamic> toArgs() {
    return [
      id,
      title,
      data,
      syncId,
      favourite,
      createdAt != null ? createdAt.millisecondsSinceEpoch : null,
      updatedAt != null ? updatedAt.millisecondsSinceEpoch : null,
      isDeleted
    ];
  }

  static Future<List<Note>> fromWebUrl(String url) async {
    try {
      final response = await http.get(url);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Note.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  static Future<List<Note>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Note>[];
    try {
      objList = list
          .map((note) => Note.fromMap(note as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Note.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Note>> fromObjectList(Future<List<dynamic>> o) async {
    final data = await o;
    return await Note.fromMapList(data);
  }

  static Future<List<Note>> fromMapList(List<dynamic> data) async {
    final List<Note> objList = <Note>[];
    for (final Map map in data as List<Map>) {
      final obj = Note.fromMap(map as Map<String, dynamic>);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Note by ID if exist, otherwise returns null
  /// <param name='id'>Primary Key Value</param>
  /// <returns>returns Note if exist, otherwise returns null
  Future<Note> getById(int id) async {
    if (id == null) {
      return null;
    }
    Note obj;
    final data = await _mnNote.getById(id);
    if (data.length != 0) {
      obj = Note.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnNote.insert(this);
    } else {
      id = await _upsert();
    }

    return id;
  }

  /// saveAs Note. Returns a new Primary Key value of Note

  /// <returns>Returns a new Primary Key value of Note
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Note> as a bulk in one transaction
  /// Returns a <List<BoolResult>>
  Future<List<BoolResult>> saveAll(List<Note> notes) async {
    final results = _mnNote.saveAll(
        'INSERT OR REPLACE INTO notes (id,  title, data, syncId, favourite, createdAt, updatedAt,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
        notes);
    return results;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> _upsert() async {
    try {
      id = await _mnNote.rawInsert(
          'INSERT OR REPLACE INTO notes (id,  title, data, syncId, favourite, createdAt, updatedAt,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
          [
            id,
            title,
            data,
            syncId,
            favourite,
            createdAt != null ? createdAt.millisecondsSinceEpoch : null,
            updatedAt != null ? updatedAt.millisecondsSinceEpoch : null,
            isDeleted
          ]);
      saveResult = BoolResult(
          success: true, successMessage: 'Note id=$id updated successfuly');
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Note Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Note>> as a bulk in one transaction.
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  /// Returns a <List<BoolResult>>
  Future<List<BoolResult>> upsertAll(List<Note> notes) async {
    final results = await _mnNote.rawInsertAll(
        'INSERT OR REPLACE INTO notes (id,  title, data, syncId, favourite, createdAt, updatedAt,isDeleted)  VALUES (?,?,?,?,?,?,?,?)',
        notes);
    return results;
  }

  /// Deletes Note

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Note invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete || isDeleted) {
      return _mnNote
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnNote.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  /// Recover Note>

  /// <returns>BoolResult res.success=Recovered, not res.success=Can not recovered
  Future<BoolResult> recover([bool recoverChilds = true]) async {
    print('SQFENTITIY: recover Note invoked (id=$id)');
    {
      return _mnNote.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 0});
    }
  }

  //private NoteFilterBuilder _Select;
  NoteFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return NoteFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  NoteFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return NoteFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    favourite = favourite ?? false;
    isDeleted = isDeleted ?? false;
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion note

// region NoteField
class NoteField extends SearchCriteria {
  NoteField(this.noteFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  NoteFilterBuilder noteFB;

  NoteField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  NoteFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.EQuals,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.NotEQuals,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.EQualsOrNull,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder isNull() {
    noteFB._addedBlocks = setCriteria(
        0,
        noteFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      noteFB._addedBlocks = setCriteria(
          pFirst,
          noteFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        noteFB._addedBlocks = setCriteria(pFirst, noteFB.parameters, param,
            SqlSyntax.LessThan, noteFB._addedBlocks);
      } else {
        noteFB._addedBlocks = setCriteria(pFirst, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        noteFB._addedBlocks = setCriteria(pLast, noteFB.parameters, param,
            SqlSyntax.GreaterThan, noteFB._addedBlocks);
      } else {
        noteFB._addedBlocks = setCriteria(pLast, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks);
      }
    }
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.GreaterThan,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.LessThan,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.LessThan,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.GreaterThan,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder inValues(dynamic pValue) {
    noteFB._addedBlocks = setCriteria(
        pValue,
        noteFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }
}
// endregion NoteField

// region NoteFilterBuilder
class NoteFilterBuilder extends SearchCriteria {
  NoteFilterBuilder(Note obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Note _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  NoteFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  NoteFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  NoteFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  NoteFilterBuilder where(String whereCriteria) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter();
      _addedBlocks =
          setCriteria(0, parameters, param, '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  NoteFilterBuilder page(int page, int pagesize) {
    if (page > 0) _page = page;
    if (pagesize > 0) _pagesize = pagesize;
    return this;
  }

  /// int count = LIMIT
  NoteFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  NoteFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  NoteFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  NoteFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') orderByList.add(' $s desc ');
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  NoteFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields) {
          if (s != null && s != '') groupByList.add(' $s ');
        }
      }
    }
    return this;
  }

  NoteField setField(NoteField field, String colName, DbType dbtype) {
    return NoteField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  NoteField _id;
  NoteField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  NoteField _title;
  NoteField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  NoteField _data;
  NoteField get data {
    return _data = setField(_data, 'data', DbType.text);
  }

  NoteField _syncId;
  NoteField get syncId {
    return _syncId = setField(_syncId, 'syncId', DbType.text);
  }

  NoteField _favourite;
  NoteField get favourite {
    return _favourite = setField(_favourite, 'favourite', DbType.bool);
  }

  NoteField _createdAt;
  NoteField get createdAt {
    return _createdAt = setField(_createdAt, 'createdAt', DbType.datetime);
  }

  NoteField _updatedAt;
  NoteField get updatedAt {
    return _updatedAt = setField(_updatedAt, 'updatedAt', DbType.datetime);
  }

  NoteField _isDeleted;
  NoteField get isDeleted {
    return _isDeleted = setField(_isDeleted, 'isDeleted', DbType.bool);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List) {
          param.value = param.value
              .toString()
              .replaceAll('[', '')
              .replaceAll(']', '')
              .toString();
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value =
                  param.value == null ? null : param.value == true ? 1 : 0;
              param.value2 =
                  param.value2 == null ? null : param.value2 == true ? 1 : 0;
              break;
            case DbType.date:
            case DbType.datetime:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            whereArguments.add(param.value);
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Note._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',');
  }

  /// Deletes List<Note> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();
    if (Note._softDeleteActivated && !hardDelete) {
      r = await _obj._mnNote.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnNote.delete(qparams);
    }
    return r;
  }

  Future<BoolResult> recover() async {
    _getIsDeleted = true;
    _buildParameters();
    print('SQFENTITIY: recover Note bulk invoked');
    return _obj._mnNote.updateBatch(qparams, {'isDeleted': 0});
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from notes ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnNote.updateBatch(qparams, values);
  }

  /// This method always returns NoteObj if exist, otherwise returns null
  /// <returns>List<Note>
  Future<Note> toSingle([VoidCallback Function(Note o) note]) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnNote.toList(qparams);
    final data = await objFuture;
    Note obj;
    if (data.isNotEmpty) {
      obj = Note.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    if (note != null) {
      note(obj);
    }
    return obj;
  }

  /// This method always returns int.
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) noteCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final notesFuture = await _obj._mnNote.toList(qparams);
    final int count = notesFuture[0]['CNT'] as int;
    if (noteCount != null) {
      noteCount(count);
    }
    return count;
  }

  /// This method always returns List<Note>.
  /// <returns>List<Note>
  Future<List<Note>> toList(
      [VoidCallback Function(List<Note> o) noteList]) async {
    final data = await toMapList();
    final List<Note> notesData = await Note.fromMapList(data);
    if (noteList != null) noteList(notesData);
    return notesData;
  }

  /// This method always returns Json String
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method always returns Json String.
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChilds(false, true));
    }
    return json.encode(list);
  }

  /// This method always returns List<dynamic>.
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnNote.toList(qparams);
  }

  /// Returns List<DropdownMenuItem<Note>>
  Future<List<DropdownMenuItem<Note>>> toDropDownMenu(String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<Note>> o)
          dropDownMenu]) async {
    _buildParameters();
    final notesFuture = _obj._mnNote.toList(qparams);

    final data = await notesFuture;
    final int count = data.length;
    final List<DropdownMenuItem<Note>> items = []..add(DropdownMenuItem(
        value: Note(),
        child: Text('Select Note'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: Note.fromMap(data[i] as Map<String, dynamic>),
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// Returns List<DropdownMenuItem<int>>
  Future<List<DropdownMenuItem<int>>> toDropDownMenuInt(
      String displayTextColumn,
      [VoidCallback Function(List<DropdownMenuItem<int>> o)
          dropDownMenu]) async {
    _buildParameters();
    qparams.selectColumns = ['id', displayTextColumn];
    final notesFuture = _obj._mnNote.toList(qparams);

    final data = await notesFuture;
    final int count = data.length;
    final List<DropdownMenuItem<int>> items = []..add(DropdownMenuItem(
        value: 0,
        child: Text('Select Note'),
      ));
    for (int i = 0; i < count; i++) {
      items.add(
        DropdownMenuItem(
          value: data[i]['id'] as int,
          child: Text(data[i][displayTextColumn].toString()),
        ),
      );
    }
    if (dropDownMenu != null) {
      dropDownMenu(items);
    }
    return items;
  }

  /// This method always returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) _buildParameters();
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnNote.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject(
      [VoidCallback Function(List<dynamic> o) listObject]) async {
    _buildParameters();

    final objectFuture = _obj._mnNote.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    if (listObject != null) {
      listObject(objectsData);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Note.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnNote.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion NoteFilterBuilder

// region NoteFields
class NoteFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField _fData;
  static TableField get data {
    return _fData = _fData ?? SqlSyntax.setField(_fData, 'data', DbType.text);
  }

  static TableField _fSyncId;
  static TableField get syncId {
    return _fSyncId =
        _fSyncId ?? SqlSyntax.setField(_fSyncId, 'syncId', DbType.text);
  }

  static TableField _fFavourite;
  static TableField get favourite {
    return _fFavourite = _fFavourite ??
        SqlSyntax.setField(_fFavourite, 'favourite', DbType.bool);
  }

  static TableField _fCreatedAt;
  static TableField get createdAt {
    return _fCreatedAt = _fCreatedAt ??
        SqlSyntax.setField(_fCreatedAt, 'createdAt', DbType.datetime);
  }

  static TableField _fUpdatedAt;
  static TableField get updatedAt {
    return _fUpdatedAt = _fUpdatedAt ??
        SqlSyntax.setField(_fUpdatedAt, 'updatedAt', DbType.datetime);
  }

  static TableField _fIsDeleted;
  static TableField get isDeleted {
    return _fIsDeleted = _fIsDeleted ??
        SqlSyntax.setField(_fIsDeleted, 'isDeleted', DbType.integer);
  }
}
// endregion NoteFields

//region NoteManager
class NoteManager extends SqfEntityProvider {
  NoteManager() : super(MyDbModel(), tableName: _tableName, colId: _colId);
  static String _tableName = 'notes';
  static String _colId = 'id';
}

//endregion NoteManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
